var Opcode = {
    WELCOME: 0,
    LOBBY: 1,
    START_GAME: 2,
    PLAYER_LIST: 3,
    PLAYER_UPDATE: 4,
    GO: 5,
    DEATH: 6,
    THROW: 7,
    ROUND_FINISH: 8,
    GAME_FINISH: 9,
    BLOCK_SMASH: 10,
    SCOREBOARD: 11,
    LOAD_COMPLETE_NOTIFY: 12,
    COUNTDOWN_START: 13
};